const assert=require('node:assert/strict');
const {webkit,chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:8080';
(async()=>{for(const engine of (process.env.BROWSER_ENGINE?[process.env.BROWSER_ENGINE]:['chromium','webkit']))for(const mobile of [false,true]){const browser=await ({webkit,chromium}[engine]).launch(process.env.CHROMIUM_EXECUTABLE&&engine==='chromium'?{executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{});const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile,hasTouch:mobile});if(engine==='chromium')await context.grantPermissions(['clipboard-read','clipboard-write']);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForSelector('#add');
// IDs remain stable after inline editing; retrieve them via the rendered input.
const byKey=async key=>{const id=await page.locator('.node').evaluateAll((els,k)=>els.find(e=>e.querySelector('.key').value===k)?.id,key);assert.ok(id,key);return page.locator(`[id="${id}"]`);};
const create=async(type,key,value)=>{await page.locator('#add').click();assert.equal(await page.locator('#palette').isVisible(),true);await page.locator(`[data-type="${type}"]`).filter({hasNot:page.locator('input')}).click();const el=page.locator('.node').last();await el.locator('.key').fill(key);if(value!==undefined)await el.locator('.value').fill(value);await el.locator('.key').blur();return byKey(key);};
const cdp=engine==='chromium'&&mobile?await context.newCDPSession(page):null;
const move=async(x,y,tx,ty,cancel=false)=>{if(cdp){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=12;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+(tx-x)*i/12,y:y+(ty-y)*i/12}]});await cdp.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});}else{await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(tx,ty,{steps:12});await page.mouse.up();}};
const drag=async(from,to)=>{const a=await from.boundingBox(),b=await to.boundingBox();assert.ok(a&&b);await move(a.x+a.width/2,a.y+a.height/2,b.x+b.width/2,b.y+b.height/2);};
const json=async()=>JSON.parse(await page.locator('#json-output').inputValue());
await create('object','Hangar');await create('list','Veicoli');await drag((await byKey('Veicoli')).locator('.connect'),(await byKey('Hangar')).locator('.socket'));assert.deepEqual(await json(),{Hangar:{Veicoli:[]}});
await create('text','TIE','Caccia imperiale');await drag((await byKey('TIE')).locator('.connect'),(await byKey('Veicoli')).locator('.socket'));assert.deepEqual(await json(),{Hangar:{Veicoli:['Caccia imperiale']}});
await page.locator('#fit').click();let h=(await byKey('Hangar')).locator('.handle');let r=await h.boundingBox();await move(r.x+30,r.y+15,r.x+65,r.y+40);assert.deepEqual(await json(),{Hangar:{Veicoli:['Caccia imperiale']}});
await page.locator('#show-json').click();assert.equal(await page.locator('#json-sheet').isVisible(),true);await page.locator('#copy').click();await page.waitForFunction(()=>/Copiato|Selezionato/.test(document.querySelector('#copy').textContent));assert.match(await page.locator('#copy').textContent(),/Copiato|Selezionato/);if(engine==='chromium')assert.deepEqual(JSON.parse(await page.evaluate(()=>navigator.clipboard.readText())),await json());await page.locator('#close-json').click();
await (await byKey('TIE')).locator('.value').fill('Interceptor');assert.deepEqual(await json(),{Hangar:{Veicoli:['Interceptor']}});await (await byKey('TIE')).locator('.disconnect').click();assert.deepEqual(await json(),{Hangar:{Veicoli:[]},TIE:'Interceptor'});
await (await byKey('TIE')).locator('.connect').click();await (await byKey('Veicoli')).locator('.socket').click();assert.deepEqual(await json(),{Hangar:{Veicoli:['Interceptor']}});await page.reload();await page.waitForSelector('.node');assert.deepEqual(await json(),{Hangar:{Veicoli:['Interceptor']}});
await page.screenshot({path:`/tmp/json-drop-${mobile?'mobile':'desktop'}.png`});
if(cdp){const before=await (await byKey('Hangar')).boundingBox();await move(before.x+30,before.y+15,before.x+55,before.y+35,true);assert.deepEqual(await (await byKey('Hangar')).boundingBox(),before);assert.equal(await page.evaluate(()=>window.scrollY),0);}
if(mobile){await page.setViewportSize({width:844,height:390});assert.equal(await page.locator('#add').isVisible(),true);await page.setViewportSize({width:390,height:844});}
await page.locator('#reset').click();await page.locator('#cancel-reset').click();assert.equal(await page.locator('.node').count(),3);await page.locator('#reset').click();await page.locator('#confirm-reset').click();assert.equal(await page.locator('.node').count(),0);assert.deepEqual(await json(),{});await page.reload();assert.equal(await page.locator('.node').count(),0);assert.deepEqual(errors,[]);console.log(`PASS ${engine} ${mobile?'390×844 mobile':'1280×900 desktop'}: complete scenario, clipboard, ${cdp?'trusted touch + cancellation, ':''}reload, reset, no JS errors`);await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
